#!/bin/bash
##############################################################################################################
## Perform DBSI signal extraction for a FreeSurfer region set
##
## USAGE: dbsipreproc paramsfn
##
## AUTHOR: Shaney Flores, Washington University School of Medicine
##############################################################################################################
program=$( basename $0 )
VERSION=1.0 #original release
if [ "$1" = "-version" ]; then
	echo 'v'$VERSION
	exit 0
fi

die(){
	echo -e >&2 "$@ \n"
	exit -1
}

paramsfn=$1

################
## MAIN PROGRAM
################
mkdir proc
cp $paramsfn proc/
cd proc

########################################
## convert T1/wmparc to usable format 
dbsipreproc $paramsfn || die "$program ERROR: dbsipreproc failed"

########################################
## create ROI masks from wmparc
createFSmasks $paramsfn || die "$program ERROR: createFSmasks failed"

########################################
## register dbsi images to participant T1 
regdbsi $paramsfn || die "$program ERROR: regdbsi failed"

########################################
## apply ROI masks to get regional values
dbsiROI $paramsfn || die "$program ERROR: dbsiROI failed"

cd ..
