#!/bin/bash
##############################################################################################################
## Preprocessing FreeSurfer output files for DBSI FS ROI analysis
##
## USAGE: dbsipreproc paramsfn
##
## AUTHOR: Shaney Flores, Washington University School of Medicine
##############################################################################################################
VERSION=1.0 # 23-Nov-20, original release

program=$( basename $0 )
idstr='$ID: '$program', v'$VERSION' Mon Nov 23 15:32:28 CDT 2020 sflores $'
echo $idstr

####################################
## GENERAL MANAGEMENT
if [ "$1" == "--version" ]; then
	echo $VERSION
	exit 0
fi

die(){
	echo -e >&2 "$@ \n"
	exit -1
}

## help menu
if [ $# -lt 1 ]; then
	echo "Usage: $program paramsfn"
	exit -1
fi

####################################
## PROCESS SPECIFIC

# Read PARAMS file
paramsfn=$1
source $paramsfn || die "$program ERROR: Cannot source params file $paramsfn"

export FREESURFER_HOME=${fs_home}

## Convert (T1|wmparc).mgz to NIFTI
convert_nii(){
	mgzroot=$1
	$fs_home/bin/mri_convert ${mgzroot}.mgz ${mgzroot}.nii || die "$program ERROR: mri convert failed"
}

####################################
## Convert FreeSurfer files to NIFTI format
cp ${fsdir}/${t1} .
cp ${fsdir}/${parc} .

convert_nii ${t1%.*}
convert_nii ${parc%.*}

####################################
## Mask images for registration
fslmaths ${parc%.*} -thr 1 -bin BrainMask
fslmaths ${t1%.*} -mas BrainMask t1_brain

####################################
## Copy over ancillary files
3dresample -master ${t1%.*}.nii -prefix $( basename ${t2wimg} ) -input ${t2wimg} 
cp ${dbsi_path}/${b0img} .
